---
title: "D607 - Assignment 2 - College Majors"
author: "Marco Castro"
date: "2024-09-07"
output:
  html_document:
    df_print: paged
---


```{r global_options, include=FALSE}
knitr::opts_chunk$set(eval = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(scales)
```


## Overview
For this assignment, 

## Normalization


```{r normalized-dataframes}

division <- tribble(
  ~division_id, ~league, ~name, 
  "ALE", "American", "East",
  "ALC", "American", "Central",
  "ALW", "American", "West",
  "NLE", "National", "East",
  "NLC", "National", "Central",
  "NLW", "National", "West"
)

division

team <- tribble(
  ~team_id, ~name, ~city, division,
  "NYY", "Yankees", "New York", "ALE",
  "BAL", "Orioles", "Baltimore", "ALE",
  "TB", "Rays", "Tampa Bay", "ALE",
  "BRS", "Red Sox", "Boston", "ALE",
  "TOR", "Blue Jays", "Toronto", "ALE",
  "GUA", "Guardians", "Cleveland", "ALC",
  "KCRL", "Royals", "Kansas City", "ALC",
  "TWN", "Twins", "Minnesota", "ALC",
  "DET", "Tigers", "Detroit", "ALC",
  "CWS", "White Sox", "Chicago", "ALC",
  "HOU", "Astros", "Houston", "ALW",
  "SEA", "Mariners", "Seattle", "ALW",
  "TEX", "Rangers", "Texas", "ALW",
  "OAK", "Athletics", "Oakland", "ALW",
  "LAA", "Angels", "Los Angeles", "ALW",
  "PHI", "Phillies", "Philadelphia", "NLE",
  "NYM", "Mets", "New York", "NLE",
  "ATL", "Braves", "Atlanta", "NLE",
  "WSH", "Nationals", "Washington Nationals", "NLE",
  "MIA", "Marlins", "Miami", "NLE",
  "BRW", "Brewers", "Milwaukee", "NLC",
  "CHC", "Cubs", "Chicago", "NLC",
  "STL", "Cardinals", "St. Louis", "NLC",
  "CIN", "Reds", "Cincinnati", "NLC",
  "PIT", "Pirates", "Pittsburgh", "NLC",
  "LAD", "Dodgers", "Los Angeles", "NLW",
  "SDP", "Padres", "San Diego", "NLW",
  "AZD", "Diamondbacks", "Arizona", "NLW",
  "SF", "Giants", "San Francisco", "NLW",
  "COR", "Rockies", "Colorado", "NLW"
)

game <- tribble(
  ~game_id, ~date, ~visitor, ~home, ~visitor_score, ~home_score,
  1, "2024-09-18", "PIT", "CIN", 3, 4,
  2, "2024-09-18", "WSH", "CHC", 7, 2,
  3, "2024-09-18", "DET", "BAL", 1, 0,
  4, "2024-09-18", "TOR", "TB", 2, 3,
  5, "2024-09-18", "PHI", "MYN", 4, 3,
  6, "2024-09-19", "PIT", "CIN", 1, 2,
  7, "2024-09-19", "WSH", "CHC", 2, 0,
  8, "2024-09-19", "DET", "BAL", 2, 3,
  9, "2024-09-19", "TOR", "TB", 1, 5,
  10, "2024-09-19", "PHI", "MYN", 8, 10,
  11, "2024-09-20", "PIT", "CIN", 2, 3,
  12, "2024-09-20", "WSH", "CHC", 2, 6,
  13, "2024-09-20", "DET", "BAL", 4, 1,
  14, "2024-09-20", "TOR", "TB", 5, 3,
  15, "2024-09-20", "PHI", "MYN", 2, 12,
  16, "2024-09-21", "PIT", "CIN", 1, 7,
  17, "2024-09-21", "WSH", "CHC", 5, 1,
  18, "2024-09-21", "DET", "BAL", 6, 4,
  19, "2024-09-21", "TOR", "TB", 2, 3,
  20, "2024-09-21", "PHI", "MYN", 3, 6,
)

game

```

## Character Manipulation
```{r import-prep-data}

# load data from 538 github page
college_majors <- read_csv("https://raw.githubusercontent.com/fivethirtyeight/data/refs/heads/master/college-majors/majors-list.csv")

college_majors_data_statistics |>
  select(matches("DATA"|"STATISTICS"))

```

## Observations 


## Conclusion

